// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DoesAppHaveDir():Promise<boolean>;

export function ReadAppConfig():Promise<string>;

export function ReadAppFiles():Promise<string>;

export function ReadUsers():Promise<Array<main.User>>;
