// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DoesAppHaveDir() {
  return window['go']['main']['App']['DoesAppHaveDir']();
}

export function ReadAppConfig() {
  return window['go']['main']['App']['ReadAppConfig']();
}

export function ReadAppFiles() {
  return window['go']['main']['App']['ReadAppFiles']();
}

export function ReadUsers() {
  return window['go']['main']['App']['ReadUsers']();
}
