// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ReadAppConfig():Promise<string>;

export function ReadAppFiles():Promise<string>;

export function RequestDir():Promise<string>;
