// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ReadAppConfig() {
  return window['go']['main']['FileManager']['ReadAppConfig']();
}

export function ReadAppFiles() {
  return window['go']['main']['FileManager']['ReadAppFiles']();
}

export function RequestDir() {
  return window['go']['main']['FileManager']['RequestDir']();
}
